# Generated by Django 6.0.7 on 2026-08-04 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cell_phone', models.CharField(max_length=10, unique=True, verbose_name='Cell phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of account creation')),
                ('preffered_lang', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English')], default='uk', max_length=5, verbose_name='Language')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AstroUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Are notifications enabled')),
                ('gender', models.CharField(choices=[('N', 'Prefer not to say'), ('M', 'Male'), ('F', 'Female')], default='N', verbose_name='Gender')),
                ('sun_sign', models.CharField(choices=[('aries', 'Aries ♈'), ('taurus', 'Taurus ♉'), ('gemini', 'Gemini ♊'), ('cancer', 'Cancer ♋'), ('leo', 'Leo ♌'), ('virgo', 'Virgo ♍'), ('libra', 'Libra ♎'), ('scorpio', 'Scorpio ♏'), ('sagittarius', 'Sagittarius ♐'), ('capricorn', 'Capricorn ♑'), ('aquarius', 'Aquarius ♒'), ('pisces', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Sun Sign')),
                ('moon_sign', models.CharField(choices=[('aries', 'Aries ♈'), ('taurus', 'Taurus ♉'), ('gemini', 'Gemini ♊'), ('cancer', 'Cancer ♋'), ('leo', 'Leo ♌'), ('virgo', 'Virgo ♍'), ('libra', 'Libra ♎'), ('scorpio', 'Scorpio ♏'), ('sagittarius', 'Sagittarius ♐'), ('capricorn', 'Capricorn ♑'), ('aquarius', 'Aquarius ♒'), ('pisces', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Moon Sign')),
                ('asc_sign', models.CharField(choices=[('aries', 'Aries ♈'), ('taurus', 'Taurus ♉'), ('gemini', 'Gemini ♊'), ('cancer', 'Cancer ♋'), ('leo', 'Leo ♌'), ('virgo', 'Virgo ♍'), ('libra', 'Libra ♎'), ('scorpio', 'Scorpio ♏'), ('sagittarius', 'Sagittarius ♐'), ('capricorn', 'Capricorn ♑'), ('aquarius', 'Aquarius ♒'), ('pisces', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Ascendant Sign')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
