# Generated by Django 6.1 on 2026-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_custom_migtations'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrouser',
            name='iana_timezone',
            field=models.CharField(blank=True, max_length=38, null=True, verbose_name='IANA timezone identifier'),
        ),
        migrations.AddField(
            model_name='astrouser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='astrouser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='astrouser',
            name='time_of_birth',
            field=models.TimeField(blank=True, null=True, verbose_name='Time of birth'),
        ),
        migrations.AlterField(
            model_name='astrouserprofile',
            name='asc_sign',
            field=models.CharField(choices=[('Ari', 'Aries ♈'), ('Tau', 'Taurus ♉'), ('Gem', 'Gemini ♊'), ('Can', 'Cancer ♋'), ('Leo', 'Leo ♌'), ('Vir', 'Virgo ♍'), ('Lib', 'Libra ♎'), ('Sco', 'Scorpio ♏'), ('Sag', 'Sagittarius ♐'), ('Cap', 'Capricorn ♑'), ('Aqu', 'Aquarius ♒'), ('Pis', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Ascendant Sign'),
        ),
        migrations.AlterField(
            model_name='astrouserprofile',
            name='moon_sign',
            field=models.CharField(choices=[('Ari', 'Aries ♈'), ('Tau', 'Taurus ♉'), ('Gem', 'Gemini ♊'), ('Can', 'Cancer ♋'), ('Leo', 'Leo ♌'), ('Vir', 'Virgo ♍'), ('Lib', 'Libra ♎'), ('Sco', 'Scorpio ♏'), ('Sag', 'Sagittarius ♐'), ('Cap', 'Capricorn ♑'), ('Aqu', 'Aquarius ♒'), ('Pis', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Moon Sign'),
        ),
        migrations.AlterField(
            model_name='astrouserprofile',
            name='sun_sign',
            field=models.CharField(choices=[('Ari', 'Aries ♈'), ('Tau', 'Taurus ♉'), ('Gem', 'Gemini ♊'), ('Can', 'Cancer ♋'), ('Leo', 'Leo ♌'), ('Vir', 'Virgo ♍'), ('Lib', 'Libra ♎'), ('Sco', 'Scorpio ♏'), ('Sag', 'Sagittarius ♐'), ('Cap', 'Capricorn ♑'), ('Aqu', 'Aquarius ♒'), ('Pis', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Sun Sign'),
        ),
    ]
