# Generated by Django 6.0.7 on 2026-08-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_astrouser_iana_timezone_astrouser_latitude_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='astrouserprofile',
            constraint=models.CheckConstraint(condition=models.Q(('asc_sign__in', ['Ari', 'Tau', 'Gem', 'Can', 'Leo', 'Vir', 'Lib', 'Sco', 'Sag', 'Cap', 'Aqu', 'Pis', 'unknown']), ('moon_sign__in', ['Ari', 'Tau', 'Gem', 'Can', 'Leo', 'Vir', 'Lib', 'Sco', 'Sag', 'Cap', 'Aqu', 'Pis', 'unknown']), ('sun_sign__in', ['Ari', 'Tau', 'Gem', 'Can', 'Leo', 'Vir', 'Lib', 'Sco', 'Sag', 'Cap', 'Aqu', 'Pis', 'unknown'])), name='valid_profile_zodiac_signs'),
        ),
    ]
