# Generated by Django 6.0.7 on 2026-08-19 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('aries', 'Aries ♈'), ('taurus', 'Taurus ♉'), ('gemini', 'Gemini ♊'), ('cancer', 'Cancer ♋'), ('leo', 'Leo ♌'), ('virgo', 'Virgo ♍'), ('libra', 'Libra ♎'), ('scorpio', 'Scorpio ♏'), ('sagittarius', 'Sagittarius ♐'), ('capricorn', 'Capricorn ♑'), ('aquarius', 'Aquarius ♒'), ('pisces', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Sign')),
                ('category', models.CharField(choices=[('general', 'General'), ('career', 'Career'), ('relationships', 'Relationships'), ('finance', 'Finance')], default='general', max_length=13, verbose_name='Category')),
                ('forecast_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=7, verbose_name='Forecast Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CustomUser')),
            ],
        ),
    ]
