# Generated by Django 6.0.7 on 2026-08-20 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='forecastpreference',
            constraint=models.UniqueConstraint(fields=('user', 'sign', 'category', 'forecast_type'), name='unique_forecast_preferences'),
        ),
    ]
