# Generated by Django 6.0.7 on 2026-08-21 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_forecastpreference_unique_forecast_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastpreference',
            options={'verbose_name': 'Forecast Preference', 'verbose_name_plural': 'Forecast Preferences'},
        ),
        migrations.RemoveConstraint(
            model_name='forecastpreference',
            name='unique_forecast_preferences',
        ),
        migrations.AddConstraint(
            model_name='forecastpreference',
            constraint=models.UniqueConstraint(fields=('user', 'sign', 'category', 'forecast_type'), name='unique_user_sign_category_forecast_type'),
        ),
    ]
