# Generated by Django 6.1 on 2026-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_alter_forecastpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastpreference',
            name='sign',
            field=models.CharField(choices=[('Ari', 'Aries ♈'), ('Tau', 'Taurus ♉'), ('Gem', 'Gemini ♊'), ('Can', 'Cancer ♋'), ('Leo', 'Leo ♌'), ('Vir', 'Virgo ♍'), ('Lib', 'Libra ♎'), ('Sco', 'Scorpio ♏'), ('Sag', 'Sagittarius ♐'), ('Cap', 'Capricorn ♑'), ('Aqu', 'Aquarius ♒'), ('Pis', 'Pisces ♓'), ('unknown', 'Not defined yet')], default='unknown', max_length=15, verbose_name='Sign'),
        ),
    ]
