# Generated by Django 6.0.7 on 2026-08-31 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_alter_forecastpreference_sign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='forecastpreference',
            constraint=models.CheckConstraint(condition=models.Q(('sign__in', ['Ari', 'Tau', 'Gem', 'Can', 'Leo', 'Vir', 'Lib', 'Sco', 'Sag', 'Cap', 'Aqu', 'Pis', 'unknown'])), name='valid_signs'),
        ),
        migrations.AddConstraint(
            model_name='forecastpreference',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['general', 'career', 'relationships', 'finance'])), name='valid_categories'),
        ),
        migrations.AddConstraint(
            model_name='forecastpreference',
            constraint=models.CheckConstraint(condition=models.Q(('forecast_type__in', ['daily', 'weekly', 'monthly'])), name='valid_forecast_type'),
        ),
    ]
