# Generated by Django 6.0.7 on 2026-08-31 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_forecastpreference_valid_signs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='forecastpreference',
            name='valid_signs',
        ),
        migrations.AddConstraint(
            model_name='forecastpreference',
            constraint=models.CheckConstraint(condition=models.Q(('sign__in', ['Ari', 'Tau', 'Gem', 'Can', 'Leo', 'Vir', 'Lib', 'Sco', 'Sag', 'Cap', 'Aqu', 'Pis', 'unknown'])), name='valid_zodiac_signs'),
        ),
    ]
