# Generated by Django 6.0.7 on 2026-09-25 15:11

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_remove_forecastpreference_valid_signs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastpreference',
            name='forecast_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/storage')), upload_to='forecasts/'),
        ),
    ]
