events {}

http {
    upstream app {
        server app:8000;
    }

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/cert.crt;
        ssl_certificate_key /etc/nginx/certs/cert.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5";
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        ssl_session_tickets off;

        location / {
            proxy_pass http://app;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-CSRFToken $cookie_csrf_token;
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS" always;
            add_header Access-Control-Header "User-Agent, X-Requested-With, Content-Type, If-Modified-Since, Cache-Control, Authorization" always;
        }

        location /static/ {
            alias /code/static/;
            autoindex on;
            types {
                text/css css;
                application/javascript js;
                image/svg+xml svg;
            }
        }
    }
}